project = "StdFace Documentation"
author = "ISSP Center"
version = '0.5.0'
release = '0.5.0'
extensions = []
templates_path = ['_templates']
exclude_patterns = ['_meta', '._*', '_build']
html_theme = 'sphinx_rtd_theme'
html_static_path = []
master_doc = 'index'
